# Generated by Django 5.1.2 on 2024-11-01 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
