# Generated by Django 5.1.2 on 2024-11-20 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0008_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='icon',
            field=models.ImageField(upload_to='Media/icons'),
        ),
    ]
