# Generated by Django 5.1.2 on 2024-11-22 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0009_alter_categories_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
