# Generated by Django 5.1.2 on 2024-11-22 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0011_instructor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='author_profile',
            field=models.ImageField(blank=True, null=True, upload_to='Media/author'),
        ),
    ]
