# Generated by Django 5.1.2 on 2024-11-22 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0012_alter_instructor_author_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='author_profile',
            field=models.ImageField(blank=True, default='default_profile.png', null=True, upload_to='Media/author'),
        ),
    ]
