# Generated by Django 5.1.2 on 2024-11-23 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0013_alter_instructor_author_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='author_profile',
            field=models.ImageField(blank=True, null=True, upload_to='Media/author'),
        ),
    ]
