# Generated by Django 5.1.2 on 2024-11-23 04:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0014_alter_instructor_author_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='author_profile',
            field=models.ImageField(blank=True, null=True, upload_to='Media/instructor'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='instructor', to=settings.AUTH_USER_MODEL),
        ),
    ]
