# Generated by Django 5.1.2 on 2024-11-25 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0016_alter_course_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='author_profile',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='name',
        ),
    ]
