# Generated by Django 5.0.6 on 2024-12-31 06:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0018_otpmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseresource',
            name='courser',
        ),
        migrations.AddField(
            model_name='courseresource',
            name='course',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, to='testapp.course'),
            preserve_default=False,
        ),
    ]
