# Generated by Django 5.0.6 on 2024-12-31 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0019_remove_courseresource_courser_courseresource_course'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseResource',
        ),
    ]
