# Generated by Django 5.0.6 on 2024-12-31 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0021_courseresource'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseResource',
        ),
    ]
