# Generated by Django 5.0.6 on 2024-12-31 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0023_courseresource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseresource',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
