# Generated by Django 5.0.6 on 2025-01-05 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0031_quizanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizanswer',
            name='selected_option',
            field=models.IntegerField(blank=True, choices=[(1, 'Option 1'), (2, 'Option 2'), (3, 'Option 3'), (4, 'Option 4')], null=True),
        ),
    ]
