# Generated by Django 5.1.4 on 2025-01-16 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0034_alter_quizresult_correct_answers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='images/teachers/default_profile.jpg', upload_to='profile_images/'),
        ),
    ]
