# Generated by Django 5.1.4 on 2025-01-20 11:55

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0036_alter_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_file', models.FileField(upload_to='certificates/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])])),
                ('verified', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('quiz_result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='testapp.quizresult')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_certificates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
