# Generated by Django 5.1.4 on 2025-01-20 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0037_quiz_published_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='uploaded',
            field=models.BooleanField(default=False),
        ),
    ]
